title: "MedPay Saúde - Documentação"
description: "Documentação completa do projeto MedPay Saúde - Plataforma de intermediação de pagamentos para saúde"
remote_theme: pmarsceill/just-the-docs

# Color scheme: light or dark
color_scheme: dark

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Repositório GitHub":
    - "//github.com/MolinariBR/MedPay"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Sort order for navigation links
nav_sort: case_insensitive

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2024 Tria Inova. Distribuído pela licença MIT."

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag